---
title: "Publication Figures"
author: "-----"
date: "02/24/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Environment Setup: 

Loading libraries
```{r}
library(mgcv)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(ncf) 
library(sf)
library(sp)
library(ncf) 
library(spdep)
```

Loading data 
```{r}
setwd("~/Desktop/Spatial Datasets") ### Adjust to reflect where data is stored 

# Load data for each sampled point in "ribbon" along transects
all_transects<-readRDS("all_transects.RDS")
all_transects <- all_transects %>% mutate(landcover=factor(landcover))

# Load data for each flax population
all_populations<-readRDS("all_populations.RDS")
all_populations<-subset(all_populations,density>0)
all_populations <- all_populations %>% mutate(prevalence = num.D/density) 

# Load non-processed flax population field data 
flax_pops <- read.csv("landscape_transects.csv")
flax_pops$transect <- as.factor(flax_pops$transect)
flax_pops <- flax_pops %>% dplyr::select(transect, start.long, start.lat, num.H, num.D) %>% dplyr::group_by(transect) %>% head(-1) 
flax_pops$subpop.incidence <- as.integer(flax_pops$num.D > 0)
flax_pops$subpop.prevalence <- (flax_pops$num.D / (flax_pops$num.D + flax_pops$num.H))

```

# Figure 2: 

```{r}
model <- gam(data = all_transects, flax.presence ~ s(elevation, k=4) + s(slope, k=5) + s(slope_westness, k=4) + s(slope_southness, k =4) +  factor(landcover), family = binomial(link=logit))
gam.check(model)
summary(model)


# A: 
plot(model,select =1, shade = T, cex.main = 2, cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5,main = "Elevation", ylab = "s(Elevation)", xlab = "Elevation (m)")
text(x = 3900, cex = 1.25, y = 1, substitute(paste(bold("p < 0.001"))))


#B: 
plot(model, select = 3, shade = T, ylim = c(-2,1), col = "red" , cex.main = 2,cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5, main = "Slope Aspect", ylab = "s(Slope Aspect)", xlab = "Slope Aspect")
par(new = T)
plot(model, select = 4, shade = T, lwd = 1.5, col = "blue", ylab="", xlab="", yaxt="n", xaxt="n", ylim = c(-2,1), xlim=c(-1,1))
legend(-0.05, -1.5, legend=c("Western Aspect (E->W)", "Southern Aspect (N -> S)"),
       col=c("red", "blue"), lty=1:1, cex=1.15)
text(x = 0.85, y = 0.7, cex = 1.25,  substitute(paste(bold("p < 0.001"))))
text(x = 0.85, y = -0.2, cex = 1.25,  substitute(paste(bold("p < 0.001"))))

#C: 
plot(model, select=2,cex.main = 2, shade =T,cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5, ylim = c(-2,2),main = "Slope Grade", ylab = "s(Slope Grade)", xlab = "Slope Grade (째)")
text(x = 60, y = 1.6, cex = 1.25, substitute(paste(bold("p < 0.001"))))

#D
dev.off()
data1 <- data.frame(
    group= unique(all_populations$mode.landcover) %>% sort(),
    value=all_populations %>% count(mode.landcover) %>% pull(n))
xlabelss <- c("Evergreen Shrubbery", "Decidious Trees", "Open Meadow", "Rocky Soil", "Decidious Shrubbery")
data1$newx = str_wrap(xlabelss, width = 10)
par(mar=c(15,12,6,10))
dev.new(width=9, height=5)
barplot(100* data1$value / sum(data1 %>% pull(value)), cex.main = 2, cex.lab = 1.25, names =  data1$newx, main = "Preferred Flax Landcover", cex.names=1, font = 2, ylab = substitute(paste(bold("Percentage of Observed Flax"))))
dev.off()
```



# Figure 3: 
```{r}

dev.new(width=5, height=5)
par(mfrow = c(2, 3))


model2 <- gam(data = all_populations, incidence ~ s(elevation) + s(slope) + s(slope.westness) + s(slope.southness) + s(density, k = 4) +  factor(mode.landcover), family = binomial(link=logit))
gam.check(model2)
summary(model2) 

#A: 
plot(model2, select = 1, shade =T, cex.main = 2,cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5,  main = "Presence ~ Elevation ", ylab = "s(Elevation)", xlab = "Elevation (m)")
rug(jitter(all_populations$elevation))
text(x = 3550, y = 1.6, cex = 1.25, substitute(paste(bold("p = 0.1426"))))


#B: 
plot(model2, select = 3, shade = T, ylim = c(-5,5),xlim=c(-1,1), col = "red" , cex.main = 2, cex.axis = 1.25, cex.lab = 1.5,  main = "Presence ~ Slope Aspect", ylab = "s(Slope Aspect)", xlab = "Slope Aspect", lwd =2)
par(new = T)
plot(model2, select = 4, shade = F, col = "blue", ylab="", xlab="", yaxt="n", xaxt="n", ylim = c(-5,5), xlim=c(-1,1), lwd = 3)
rug(jitter(all_populations$slope.southness), col = "blue", lwd = 2)
legend(-1, -3, legend=c("Western Aspect (E -> W)", "Southern Aspect (N -> S)"),
       col=c("red", "blue"), lty=1:1, cex=1.15)

#C: 
plot(model2, select=2,cex.main = 2, shade =T, cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5,  main = "Presence ~ Slope Grade", ylab = "s(Slope Grade)", xlab = "Slope Grade (째)")
text(x = 35, y = 4, cex = 1.25, substitute(paste(bold("p < 0.05"))))




model3 <- gam(data=all_populations, prevalence ~ s(elevation) + s(slope) + s(slope.westness) + s(slope.southness) +  factor(mode.landcover) + s(density, k =20))
gam.check(model3) 
summary(model3) 

dev.new(width=5, height=5)

#D: 
plot(model3, select = 1, shade =T, cex.main = 2,cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5,  main = "Prevalence ~ Elevation ", ylab = "s(Elevation)", xlab = "Elevation (m)")
text(x = 3550, y = 0.015, cex = 1.25, substitute(paste(bold("p = 0.587"))))

#E: 
plot(model3, select = 3, shade = T, ylim = c(-0.1,0.1),xlim=c(-1,1), col = "red" , cex.main = 2, cex.axis = 1.25, cex.lab = 1.5, main = "Prevalence ~ Slope Aspect", ylab = "s(Slope Aspect)", xlab = "Slope Aspect", lwd = 2)
par(new = T)
plot(model3, select = 4, shade = F, col = "blue", ylab="", xlab="", yaxt="n", xaxt="n", ylim = c(-0.1,0.1), xlim=c(-1,1), lwd = 3)
rug(jitter(all_populations$slope.westness), col = "red", lwd = 2)
rug(jitter(all_populations$slope.southness), col = "blue", lwd = 2)
legend(-1, -0.06, legend=c("Western Aspect (E->W)", "Southern Aspect (N -> S)"),
       col=c("red", "blue"), lty=1:1, cex=1.15)

#F: 
plot(model3, select=2,cex.main = 2, shade =T, cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5,  main = "Prevalence ~ Slope Grade", ylab = "s(Slope Grade)", xlab = "Slope Grade (째)")
text(x = 32, y = 0.025, cex = 1.25, substitute(paste(bold("p = 0.656"))))



```

Table 1: 
```{r}
data1 <- data.frame(
    group= unique(all_populations$mode.landcover) %>% sort(),
    value=(all_populations %>% count(mode.landcover) %>% pull(n)) / length(all_populations$transect)) 
xlabelss <- c("Evergreen Shrubbery", "Decidious Trees", "Open Meadow", "Rocky Soil", "Decidious Shrubbery")
data1$newx = str_wrap(xlabelss, width = 10)


all_diseased_populations <- all_populations %>% filter(incidence >0) 
  data2 <- data.frame(
    group= unique(all_diseased_populations$mode.landcover) %>% sort(),
    value=(all_diseased_populations %>% count(mode.landcover) %>% pull(n)) /
        length(all_diseased_populations$transect))
  xlabelss2 <- c("Evergreen Shrubbery", "Decidious Trees", "Open Meadow", "Rocky Soil")
  data2$newx = str_wrap(xlabelss2, width = 10)

 
prev_cutoffs <- all_populations %>% filter(prevalence > 0) %>% pull(prevalence) %>% quantile(c(0, 1/3, 2/3))
  
prev1 <- all_populations %>% filter(prevalence >= prev_cutoffs[1]) %>% filter(prevalence < prev_cutoffs[2])
  data5 <- data.frame(
    group= unique(prev1$mode.landcover) %>% sort(),
    value=(prev1 %>% count(mode.landcover) %>% pull(n)) / length(prev1$transect))
  
prev2 <- all_populations %>% filter(prevalence >= prev_cutoffs[2]) %>% filter(prevalence < prev_cutoffs[3])
  data3 <- data.frame(
    group= unique(prev2$mode.landcover) %>% sort(),
    value=(prev2 %>% count(mode.landcover) %>% pull(n)) / length(prev2$transect))
 
  
prev3 <- all_populations %>% filter(prevalence >= prev_cutoffs[3]) 
  data4 <- data.frame(
    group= unique(prev3$mode.landcover) %>% sort(),
    value=(prev3 %>% count(mode.landcover) %>% pull(n)) / length(prev3$transect))
 
 prev1$mode.landcover %>% length()
 prev2$mode.landcover %>% length()
 prev3$mode.landcover %>% length()

```


```{r}
dev.new(width=5, height=5)

# A: Presence: 
spline_pres =spline.correlog(x=flax_pops$start.long, y=flax_pops$start.lat,
                              z=flax_pops$subpop.incidence, xmax=30, latlon = T, na.rm = T)
summary(spline_pres)
plot(spline_pres,  cex.main = 2,cex.axis = 1.25, cex.lab = 1.5,  main = "Presence Correlogram", ylab = "Presence Spatial Correlation", xlab = "Distance (m)")

# B: Prevalence: 
spline_prev =spline.correlog(x=flax_pops$start.long, y=flax_pops$start.lat,
                                 z=flax_pops$subpop.prevalence, xmax = 30, latlon = T, na.rm = T)
    summary(spline_prev)
    plot(spline_prev,  cex.main = 2,cex.axis = 1.25, cex.lab = 1.5,  main = "Prevalence Correlogram", ylab = "Prevalence Spatial Correlation", xlab = "Distance (m)")

#C: 
inc_den <- gam(data=all_populations, incidence ~ s(density, k =4)+ s(elevation) + s(slope) + s(slope.westness) + s(slope.southness) +  factor(mode.landcover), binomial)
summary(inc_den)
plot(inc_den,  select = 1, shade = T, cex.main = 2,cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5,  main = "Presence ~ Density ", ylab = "s(Population Density)", xlab = "Population Density (n)")
text(x = 105, y = 3.5, cex = 1.25, substitute(paste(bold('p < 0.05'))))

#D: 
prev_den <- gam(data=all_populations, prevalence ~ s(density, k =4)+ s(elevation) + s(slope) + s(slope.westness) + s(slope.southness) +  factor(mode.landcover))
gam.check(prev_den)
summary(prev_den)
plot(prev_den,  select = 1, shade = T, cex.main = 2,cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5,  main = "Prevalence ~ Density ", ylab = "s(Population Density)", xlab = "Population Density (n)")
text(x = 100, y = 0.005, cex = 1.25, substitute(paste(bold('p = 0.816'))))

```




Moran's Test: 
```{r}
# Moran's test: does occurrence in one region make event in neighboring event more or less likely?
    # Adapted from https://mgimond.github.io/simple_moransI_example/
    df <- flax_pops %>% st_as_sf(coords = c("start.long", "start.lat"), dim = "XY")
      # plot(df[4], pal = (c("black", "red")))
    df1 <- as(df, "Spatial")
    coo <- coordinates(df1)
    S.dist  <-  dnearneigh(coo, longlat = TRUE, 0, 0.25)  # 250m radius 
    lw <- nb2listw(S.dist, style="W",zero.policy=TRUE) 
   
    prev_MI  <-  moran.mc(df1$subpop.prevalence, lw, nsim=1000,zero.policy=T) 
    plot(prev_MI, main="", las=1) 
    prev_MI
    
    inc_MI  <-  moran.mc(df1$subpop.incidence, lw, nsim=1000,zero.policy=T) 
    plot(inc_MI, main="", las=1) 
    inc_MI

```



Additional Density Analyses: 
```{r}

population_disease_parameter <- sum(all_populations$num.D) / (sum(all_populations$num.H) + sum(all_populations$num.D))
presence.flax.rust <- rbinom(n = length(all_populations$density),all_populations$density, population_disease_parameter)
presence.flax.rust <- 1*(presence.flax.rust>0)
actual.presence.flax.rust2 <-  1*((all_populations$num.D + all_populations$incidence) > 0)
t.test(x = actual.presence.flax.rust2, y = presence.flax.rust,  "greater") 


# Check 2: 
high_density_pops <- all_populations %>% filter(density > mean(all_populations$density)) 
low_density_pops <- all_populations %>% filter(density < mean(all_populations$density))
t.test(x = high_density_pops$incidence, y = low_density_pops$incidence, alternative = "greater")

```

Figure 5A: 
```{r}
library(raster) 
flax_pops <- read.csv("landscape_transects.csv")
flax_pops$transect <- as.factor(flax_pops$transect)
flax_pops <- flax_pops %>% dplyr::select(transect, start.long, start.lat, num.H, num.D) %>% dplyr::group_by(transect) %>% head(-1) 
flax_locs <- flax_pops[, c(2,3)]
all_transects_plotting <- c('RG' , 'GL' , 'WM', 'TR' , 
                            'NP' , 'CL' , 'LG' , 'MB' , 
                            'HM' , 'CB' , 'DC' , 
                            'VB' , "CT", 'BG' , 'CM' ,'BC', 'SH')

# loading PRISM 800m mean rasters: 
setwd("~/Desktop/Spatial Datasets") 
temp <- raster("temp_raster/PRISM_tmean_30yr_normal_800mM3_annual_bil.bil", progress='text')
elevation_raster <- raster("elevation_raster/PRISM_us_dem_800m_bil.bil", progress='text')
precip_raster <- raster("precip_raster/PRISM_ppt_30yr_normal_800mM3_annual_bil.bil", progress='text')

# extracting raster data for flax locations
flax_pops$temperature <- extract(temp,flax_locs,method="simple")
flax_pops$ele2 <- extract(elevation_raster,flax_locs,method="simple")
flax_pops$precip <- extract(precip_raster,flax_locs,method="simple")


# Modeling Temperature - Elevation Relationship 
set.seed(2)
library(caret)
jd <- na.omit(flax_pops)
training.samples <- jd$temperature %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- jd[training.samples, ]
test.data <- jd[-training.samples, ]

model_new <- lm(temperature ~ poly(ele2, 4, raw = TRUE), data = jd)
summary(model_new) 
predictions <- model_new %>% predict(test.data)
model_validity <- data.frame(
  RMSE = RMSE(predictions, test.data$temperature),
  R2 = R2(predictions, test.data$temperature)
)
R2 <- paste('R^2 = ', round(model_validity$R2, 2))

# C: 
dev.new(width=5, height=5)
ggplot(flax_pops, aes(ele2, temperature) ) +
  geom_point() +
  stat_smooth(method = lm, formula = y ~ poly(x, 4, raw = TRUE)) + 
  labs(title = "Temperature ~ Elevation", x = "Elevation (m)", y = "Average Annual Temperature (C)" ) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5, size=25, face = "bold"), 
        axis.text=element_text(size=15),
          axis.title=element_text(size=20)) + 
    annotate("Text", x=3500, y=2, label= R2, size = 7) 


```


Figure 5 (rest): 
```{r}
dev.new(width=5, height=5)

#B: 
landcover3<- na.omit(all_transects %>% filter(landcover==3) %>% pull(elevation))
hist(landcover3, cex.main = 2,cex.axis = 1.25, cex.lab = 1.5, lwd = 1.5, freq=F, breaks = 7, main = "Distribution of Flax's \n Preferred Landcover", ylab = "Proportion", xlab = "Elevation (m)", xlim=c(2400, 4600))
lines(density(landcover3, bw=100), lwd = 2)

#C: 
smoothScatter(x=all_transects$elevation, y = all_transects$slope, main = "Distribution of Slope Grade \n Across Elevation ",
              xlab = "Elevation (m)", ylab = "Slope Grade (째)", cex.main = 2,cex.axis = 1.25, cex.lab=1.5)
slope_ele <- lm(all_transects$slope ~ all_transects$elevation)
summary(slope_ele)
abline(slope_ele, lwd = 3, col = "red")
text(x = 3975, y = 63, cex = 1.25, substitute(paste(bold("p < 0.001"))))


```



Appendix: 
```{r}
dev.new() 

# 1: 
flax_pops <- read.csv("landscape_transects.csv")
flax_pops$transect <- as.factor(flax_pops$transect)
flax_pops$subpop.incidence <- as.integer(flax_pops$num.D > 0)
flax_pops$subpop.prevalence <- (flax_pops$num.D / (flax_pops$num.D + flax_pops$num.H))
flax_dates <- flax_pops %>%  mutate(date = date %>% as.Date(format = "%m/%d/%y"))

plot(x=flax_dates$date, y=flax_dates$subpop.prevalence,  cex.main = 2,cex.axis = 1, cex.lab = 1,  main = "Prevalence Over Time", ylab = "Rust Prevalence", xlab = "Date", pch = 16)
abline(lm(flax_dates$subpop.prevalence ~ flax_dates$date), col = "red", lwd = 2)
summary(lm(flax_dates$subpop.prevalence ~ flax_dates$date))
text(x = as.Date("2021-07-03"), y = 0.55, cex = 1.25, substitute(paste(bold("p = 0.415"))))

# 2: 
plot(x=all_populations$elevation, y=all_populations$density, 
         main = "Population Density ~ Elevation", 
         ylab = " Flax Population Density (n)", xlab = "Elevation (m)", 
         cex.main = 2,cex.axis = 1.25, cex.lab = 1.5,ylim=c(0,125), pch = 16)
    model1 <- lm(data = all_populations,density ~ elevation)
   abline(model1,col = "darkgreen", lwd = 3)
summary(model1)
text(x = 2825, y = 115, cex = 1.25, substitute(paste(bold("p = 0.1587"))))


# 3: 
smoothScatter(x=all_transects$elevation, y = all_transects$slope_westness, main = "Distribution of Observed \n Slope Westness Values", xlab = "Elevation (m)", ylab = "Slope Aspect")
smoothScatter(x=all_transects$elevation, y = all_transects$slope_southness, main = "Distribution of Observed \n Slope Southness Values", xlab = "Elevation (m)", ylab = "Slope Aspect")

# 4: 

plot(x=all_populations$elevation, y=all_populations$nearest.pop.dist,  cex.main = 1.5,cex.axis = 1, cex.lab = 1,  main = "Population Connectivity ~ Elevation", ylab = "Distance to Nearest Pop (m)", xlab = "Elevation (m)", ylim = c(0,4500), xlim=c(2700,3800))
connectivity_model <- lm(data = all_populations, nearest.pop.dist ~ elevation)
abline(connectivity_model,col = "darkgreen", lwd = 3)
summary(connectivity_model)
text(x = 2825, y = 4000, cex = 1.25, substitute(paste(bold("p = 0.426"))))


```


Post-Revision Appendix Figure 5:   
```{r}
library(cowplot)
library(gridGraphics)
dev.new() 

flax_pops <- flax_pops %>% dplyr::select(transect,date) %>% unique() %>% mutate(date = as.Date(date,format = "%m/%d/%y"))
flax_dates <- flax_pops %>% dplyr::select(transect, date)
all_data <- merge(all_populations, flax_dates, by = "transect")

ele_date <- lm(data = all_data, elevation ~ date)
summary(ele_date)
plot(all_data$date, all_data$elevation, pch = 16, cex.main = 2, cex.axis = 1, cex.lab = 1.5,  main = "Elevation Sampling", ylab = "Elevation (m)", xlab = "Date") 
abline(ele_date, col = "red", lwd = 2)
text(x = as.Date("07/26/21", format = "%m/%d/%y"), y = 2800, "p = 0.144")
a <- recordPlot()

slope_date <- lm(data = all_data, slope ~ date)
summary(slope_date)
plot(all_data$date, all_data$slope, pch = 16, cex.main = 2, cex.axis = 1, cex.lab = 1.5,  main = "Slope Sampling", ylab = "Slope Grade (degrees)", xlab = "Date") 
abline(slope_date, col = "red", lwd = 2)
text(x = as.Date("07/26/21", format = "%m/%d/%y"), y = 6, "p = 0.985")
b <- recordPlot()


slope_date <- lm(data = all_data, slope.westness ~ date)
summary(slope_date)
plot(all_data$date, all_data$slope.westness, pch = 16, cex.main = 2, cex.axis = 1, cex.lab = 1.5,  main = "Slope Westness Sampling", ylab = "Slope Westness", xlab = "Date") 
abline(slope_date, col = "red", lwd = 2)
text(x = as.Date("07/26/21", format = "%m/%d/%y"), y = -0.9, "p = 0.487")
c <- recordPlot()


slope_date <- lm(data = all_data, slope.southness ~ date)
summary(slope_date)
plot(all_data$date, all_data$slope.southness, pch = 16, cex.main = 2, cex.axis = 1, cex.lab = 1.5,  main = "Slope Southness Sampling", ylab = "Slope Southness", xlab = "Date") 
abline(slope_date, col = "red", lwd = 2)
text(x = as.Date("07/26/21", format = "%m/%d/%y"), y = -0.9, "p = 0.954")
d <- recordPlot()


landcover_date <- lm(data = all_data, mode.landcover ~ date)
summary(landcover_date)
plot(all_data$date, all_data$mode.landcover, pch = 16, cex.main = 2, cex.axis = 1, cex.lab = 1.5,  main = "Landcover Sampling", ylab = "Population Landcover Mode", xlab = "Date") 
abline(landcover_date, col = "red", lwd = 2)
text(x = as.Date("07/26/21", format = "%m/%d/%y"), y = 1, "p =  0.169")
e <- recordPlot()

dev.new() 
plot_grid(a, b, c, d, e,
          labels = 'AUTO')
```

